# Generated by Django 4.2.2 on 2023-07-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_rate_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='currency_type',
            new_name='currency',
        ),
    ]
