# Generated by Django 4.2.2 on 2023-07-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_requstresponselog_alter_contactus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requstresponselog',
            name='request_method',
            field=models.CharField(default='GET', max_length=50, verbose_name='Request method'),
        ),
    ]
