# Generated by Django 4.2.2 on 2023-08-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_alter_contactus_options_alter_rate_options_and_more'),
        ('currency', '0006_alter_requstresponselog_request_method'),
    ]

    operations = [
    ]
